apiVersion: v1
kind: Service
metadata:
  name: "ltd-proxy"
  labels:
    app.kubernetes.io/name: "ltd-proxy"
spec:
  ports:
    - name: "ltd-proxy-http"
      protocol: "TCP"
      port: 8080
      targetPort: "app"
  selector:
    app.kubernetes.io/name: "ltd-proxy"
