name: CI

"on":
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v3
        with:
          path: .tox
          # requirements/*.txt and pyproject.toml have versioning info
          # that would impact the tox environment.
          key: tox-${{ matrix.python }}-${{ hashFiles('requirements/*.txt') }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tox-${{ matrix.python }}-${{ hashFiles('requirements/*.txt') }}-

      - name: Run tox
        run: tox -e lint,typing,py,coverage-report

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Define the Docker tag
        id: vars
        run: echo ::set-output name=tag::$(scripts/docker-tag.sh "$GITHUB_HEAD_REF")

      - name: Print the tag
        id: print
        run: echo ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./  # use currently-checked out files
          file: ./Dockerfile
          push: ${{ github.repository == 'jsickcodes/ltd-proxy' }}
          tags: |
            ghcr.io/jsickcodes/ltd-proxy:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
